// app/data.ts
export const posts = [
   {
    date: "2026.Feb",
    title: "115全國專題競賽-歷程與心得",
    description: "這篇文章分享我在準備 115 全國專題賽時，從創作動機到成果展出的...",
    tags: ["Robot", "Android Studio", "Raspberry pi 4", "Triangle Robot"],
    category: "Contest",
    cover: "/115.jpg",
  },
  {
    date: "2025.Dec",
    title: "114工科技藝競賽-心路歷程",
    description: "從一年級開始參加機器人直到高三...",
    tags: ["Robot", "Labview"],
    category: "Contest",
    cover: "/114.jpg",
  },
   {
    date: "2025.Apr",
    title: "65屆北一區科展-競賽紀錄",
    description: "傳統三角故障警示牌 vs 自動化部署三角警示牌...",
    tags: ["Robot", "Triangle Robot"],
    category: "Project",
    cover: "/65.png",
  },
  {
    date: "2025.Mar",
    title: "55分區技能競賽-競賽紀錄",
    description: "分區技能競賽是一場青年好手的競賽殿堂...",
    tags: ["Robot", "Labview"],
    category: "Contest",
    cover: "/55.jpeg",
  },
  {
    date: "2025.Feb",
    title: "114全國專題競賽-歷程與心得",
    description: "這篇文章分享我在準備 114 全國專題賽時，從創作動機到成果展出的...",
    tags: ["Robot", "Labview", "medical"],
    category: "Contest",
    cover: "/114mr.jpg",
    imageClass: "object-contain bg-[#0a0a0a]",
  },
  {
    date: "2025.Feb",
    title: "2025IEYI青少年發明展-歷程與心得",
    description: "這篇文章分享我在準備設計魚菜共生的產品，數據統計...",
    tags: ["Aquaponics", "tech", "Fish"],
    category: "Project",
    cover: "/2025ieyi.png",
    imageClass: "object-contain bg-[#0a0a0a]",
  },
  {
    date: "2024.Mar",
    title: "54分區技能競賽-競賽紀錄",
    description: "高中開學半年第一次參加競賽，需要學習許多...",
    tags: ["Robot", "Labview"],
    category: "Contest",
    cover: "/54.png",
    imageClass: "object-contain bg-[#0a0a0a]",
  },
];
